baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'paper'
summaryLength = 70
refLinksErrorLevel = 'ERROR'
# refLinksNotFoundURL
[taxonomies]
  category = 'categories'
  series = 'series'
  tags = 'tags'
  product_type = 'product-types'
[params]
color = 'linen'
