baseURL = 'http://example.org/'
# languageCode = 'en-us'
defaultContentLanguage = 'en'
disableLanguages = ['fr', 'ja']
enableMissingTranslationPlaceholders = true
title = 'My New Hugo Site'
theme = 'paper'
summaryLength = 70
refLinksErrorLevel = 'ERROR'
# refLinksNotFoundURL
posts = '/posts/:year/:month/:title'
sectionPagesMenu = 'main'
staticDir = ['static1', 'static2']
# section: quote, section list: quotes
pluralizeListTitles = false
[taxonomies]
  category = 'categories'
  series = 'series'
  tags = 'tags'
  product_type = 'product-types'
[params]
  color = 'linen'
  [params.navigation]
    help = 'Help'
[languages]
  [languages.en]
    title = 'Blog'
    weight = 1
    # baseURL = 'https://example.com'
    # contentDir = 'content/en'
    languageName = 'English'
  [languages.ru]
    title = 'Блог'
    # baseURL = 'https://example.ru'
    # contentDir = 'content/ru'
    languageName = 'Русский'
    [languages.ru.params]
      help = 'Помощь'
      poli = 'Полиэ'
